manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

      # support nice_oled and nice_epaper
    - name: mctechnology17
      url-base: https://github.com/mctechnology17

    - name: urob
      url-base: https://github.com/urob

    - name: caksoylar
      url-base: https://github.com/caksoylar

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

      # support nice_oled and nice_epaper
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main

    - name: zmk-auto-layer
      remote: urob
      revision: main

    - name: zmk-tri-state
      remote: urob
      revision: main

  self:
    path: config
